export const testConst = [
  {
    title: "Watch",
    image: "https://source.unsplash.com/1d1QTXHpC6I",
    price: "25",
    category: "women's Clothing",
    description: "Elegant wristwatch with a leather strap.",
    id: "1",
  },
  {
    title: "Camera",
    image: "https://source.unsplash.com/guI3Wx1ZLhQ",
    price: "30",
    category: "electronics",
    description: "Professional DSLR camera for capturing stunning moments.",
    id: "2",
  },
  {
    title: "Laptop",
    image: "https://source.unsplash.com/az9PqKgjR4s",
    price: "20",
    category: "electronics",
    description: "Sleek and powerful laptop for work and entertainment.",
    id: "3",
  },
  {
    title: "Coffee Mug",
    image: "https://source.unsplash.com/qFp2Lh4flrM",
    price: "15",
    category: "Home",
    description: "Classic coffee mug for your favorite hot beverages.",
    id: "4",
  },
  {
    title: "Headphones",
    image: "https://source.unsplash.com/IvTzERkm42E",
    price: "40",
    category: "electronics",
    description: "High-quality headphones for an immersive audio experience.",
    id: "5",
  },
  {
    title: "Backpack",
    image: "https://source.unsplash.com/aaDc9Pzcspk",
    price: "35",
    category: "women's Clothing",
    description: "Stylish backpack for carrying your essentials on the go.",
    id: "6",
  },
  {
    title: "Sunglasses",
    image: "https://source.unsplash.com/uSWMJk7vVT4",
    price: "28",
    category: "men's Clothing",
    description: "Fashionable sunglasses for a trendy look.",
    id: "7",
  },
  {
    title: "Running Shoes",
    image: "https://source.unsplash.com/3w1ov44fSM8",
    price: "50",
    category: "men's Clothing",
    description: "Comfortable running shoes for your active lifestyle.",
    id: "8",
  },
];
export const categoryOptions = [
  { label: "electronics" },
  { label: "jewelery" },
  { label: "men's Clothing" },
  { label: "women's Clothing" },
];
